//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailwayReservation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int Id { get; set; }
        public string username { get; set; }
        public string feedback_msg { get; set; }
        public int pnr { get; set; }
        public string admin_reply { get; set; }
    
        public virtual ticket ticket { get; set; }
        public virtual User User { get; set; }
    }
}
