//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailwayReservation
{
    using System;
    using System.Collections.Generic;
    
    public partial class LostFound
    {
        public int ItemId { get; set; }
        public string ItemType { get; set; }
        public string Brand { get; set; }
        public string Colour { get; set; }
        public int train_id { get; set; }
    
        public virtual Train Train { get; set; }
    }
}
