//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailwayReservation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int ServiceId { get; set; }
        public int pnr { get; set; }
        public string Service1 { get; set; }
        public string Remark { get; set; }
        public string Status { get; set; }
    
        public virtual ticket ticket { get; set; }
    }
}
