//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railway_Reservation
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string username { get; set; }
        public string name { get; set; }
        public int age { get; set; }
        public string password { get; set; }
        public string role { get; set; }
    }
}
